# Generated by Django 5.1.5 on 2025-02-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG_CHATBOT_BACKEND_APIS', '0006_fileupload_pdf_embadding_error_or_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='pdf_embadding_status',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='pdf_embedding_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
