# Generated by Django 5.1.5 on 2025-02-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG_CHATBOT_BACKEND_APIS', '0007_remove_fileupload_pdf_embadding_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='thread_uuid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
