# Generated by Django 5.1.5 on 2025-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG_CHATBOT_BACKEND_APIS', '0008_fileupload_thread_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='thread_uuid',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='thread_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
