# Generated by Django 5.1.5 on 2025-02-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG_CHATBOT_BACKEND_APIS', '0009_remove_fileupload_thread_uuid_fileupload_thread_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_embedding_status', models.CharField(default='pending', max_length=50)),
                ('url_embedding_error_or_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='thread_id',
        ),
    ]
